# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3abe06580a5bf8f58e99bbc6fa80648c92d1774b1af8dfb63fda44d7ad1a7e71bc7dd75db8b495b8fff71bd12750f16e05f2491269dd3c735d2e6368cfc07b24

test:
  secret_key_base: ce8c508dbec8343e67286ddb84f73954a43f0d9aba0a7ad9722917a911a7da086d25bf773a10c0a75a8ebca8c506965b32880608119abbdcb75ea4bf67dd1c8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
